// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),
		//World Of Naruto
		BUILDIN_DEF(dirP,"i"),
		BUILDIN_DEF(guild_addmember,"i?"),
		BUILDIN_DEF(guild_delmember,"i???"),
		
		
		BUILDIN_DEF(duplicatecreate, "ssssiii???"),
		BUILDIN_DEF(duplicateremove, "?"),
	
	